server:
  port: 4923

logging:
  pattern:
    level: "%5p %X{CorrelationId}"
  level:
    root: warn
    org.elasticsearch.client: error
    com.k_int.rosetta: info
    com.k_int.rosetta.web.api.iiif: debug
    com.k_int.rosetta.web.iiif.presentation.v3: debug
    com.k_int.rosetta.provider.elastic: debug

management:
  endpoints:
    web:
      exposure:
        include:
          - health

springdoc:
  api-docs:
    path: /api/v1/spec

rosetta:
  cache:
    enabled: false
    use_cache_service: false
  transform:
    enabled: true
    timeout_millis: 6000
    glyphs:
      - name: jpt
        type: jpt
        properties:
          mutable: true
          file: ./config/jpt.json
          input: source
          output: detail
  provider:
    providers:
      - name: elasticsearch
        type: elasticsearch
        domainConverter: es-converter
        properties:
          host: ciim-public-es-http.etna
          port: 9200
          index: ciim
          username: elastic
          password: B56RuPS2xu2Gvev3G0g2o245
          path_config:
            paths:
              topic: "topic.summary.title.keyword"
              collection: "@hierarch.identifier.__reference_number"
              group: "@datatype.group.value"
              level: "level.value"
              type: "@datatype.actual"
              country: "place.@hierarchy.name.value.keyword"
              closure: "availability.closure.label.value.keyword"
              catalogueSource: "source.value"
  domain:
    converters:
      - name: es-converter
        type: elastic-default
