apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: etna-ingress
  namespace: etna
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: etna-apikey-auth
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /api/v1/$1
spec:
  rules:
    - http:
        paths:
          - path: /api/v1/data/(.*)
            pathType: Prefix
            backend:
              service:
                name: rosetta-service
                port:
                  name: rosetta-port