apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: etna-ingress
  namespace: etna
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: etna-apikey-auth
    konghq.com/strip-path: true
spec:
  rules:
    - http:
        paths:
          - path: /api/v1/data
            pathType: Prefix
            backend:
              service:
                name: rosetta-service
                port:
                  name: rosetta-port
          - path: /search
            pathType: Prefix
            backend:
              service:
                name: ciim-internal-es-default
                port:
                  number: 9200