apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ciim-internal
  namespace: etna
spec:
  nodeSets:
    - count: 1
      name: default
      podTemplate:
        spec:
          containers:
            - env:
                - name: ES_JAVA_OPTS
                  value: '-Xms12g -Xmx12g -Dlog4j2.formatMsgNoLookups=true'
              name: elasticsearch
              resources:
                requests:
                  memory: 12Gi