apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-cors
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  origins:
    - "*"
  credentials: true
  max_age: 3600
  preflight_continue: false
plugin: cors