apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: etna
  name: etna-deployer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eks-deployer-role
  namespace: etna
rules:
  - apiGroups: [ "", "extensions", "apps", "batch" ]
    resources:
      - "pods"
      - "deployments"
      - "statefulsets"
      - "secrets"
      - "configmaps"
      - "replicasets"
      - "cronjobs"
      - "persistentvolumeclaims"
      - "services"
      - "ingresses"
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eks-deployer-rolebinding
  namespace: etna
subjects:
  - kind: Group
    name: eks-deployer-group
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: etna-deployer
namespace: etna
roleRef:
  kind: Role
  name: eks-deployer-role
  apiGroup: rbac.authorization.k8s.io
